-- tests/epoch/services/time/conversion_spec.lua

local conversion = require('epoch.services.time.conversion')

describe("services time conversion", function()
  describe("convert_to_24_hour", function()
    it("should convert AM times correctly", function()
      assert.equals(9, conversion.convert_to_24_hour(9, "AM"))
      assert.equals(0, conversion.convert_to_24_hour(12, "AM"))
      assert.equals(1, conversion.convert_to_24_hour(1, "AM"))
    end)

    it("should convert PM times correctly", function()
      assert.equals(21, conversion.convert_to_24_hour(9, "PM"))
      assert.equals(12, conversion.convert_to_24_hour(12, "PM"))
      assert.equals(13, conversion.convert_to_24_hour(1, "PM"))
    end)
  end)

  describe("convert_to_12_hour", function()
    it("should convert midnight and noon correctly", function()
      local hour, period = conversion.convert_to_12_hour(0)
      assert.equals(12, hour)
      assert.equals("AM", period)

      hour, period = conversion.convert_to_12_hour(12)
      assert.equals(12, hour)
      assert.equals("PM", period)
    end)

    it("should convert morning hours correctly", function()
      local hour, period = conversion.convert_to_12_hour(9)
      assert.equals(9, hour)
      assert.equals("AM", period)
    end)

    it("should convert evening hours correctly", function()
      local hour, period = conversion.convert_to_12_hour(21)
      assert.equals(9, hour)
      assert.equals("PM", period)
    end)
  end)

  describe("is_valid_format", function()
    it("should validate correct 12-hour formats", function()
      assert.is_true(conversion.is_valid_format("9:00 AM"))
      assert.is_true(conversion.is_valid_format("12:30 PM"))
      assert.is_true(conversion.is_valid_format("1:15 AM"))
    end)

    it("should reject invalid formats", function()
      assert.is_false(conversion.is_valid_format("25:00 AM"))
      assert.is_false(conversion.is_valid_format("9:60 AM"))
      assert.is_false(conversion.is_valid_format("9:00"))
    end)
  end)

  describe("to_minutes_since_midnight", function()
    it("should convert times to minutes correctly", function()
      assert.equals(540, conversion.to_minutes_since_midnight("9:00 AM"))
      assert.equals(750, conversion.to_minutes_since_midnight("12:30 PM"))
      assert.equals(0, conversion.to_minutes_since_midnight("12:00 AM"))
    end)

    it("should return nil for invalid times", function()
      assert.is_nil(conversion.to_minutes_since_midnight("25:00 AM"))
      assert.is_nil(conversion.to_minutes_since_midnight("invalid"))
    end)
  end)
end)