name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    
    - name: run tests
      run: make test

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    
    - name: install lust
      run: sudo luarocks install lust
    
    - name: run coverage check
      run: make coverage

  laconic:
    name: laconic
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    
    - name: install lust
      run: sudo luarocks install lust
    
    - name: run laconic check
      run: make laconic

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    
    - name: install luacheck
      run: sudo luarocks install luacheck
    
    - name: run lint check
      run: make lint